### ISSUE TITLE
Stakeholder must not return anything

### ISSUE THREAD

**Issue by yegor256** [zerocracy/jstk#11]

**Comment by yegor256** [comment]
@rultor release, tag is `0.10`

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/jstk/issues/11#issuecomment-278384345))

Job `gh:zerocracy/jstk#11` is in scope of "C3NDPUA8L".

**Comment by 0crat** [comment]
Job `gh:zerocracy/jstk#11` is out of "C3NDPUA8L".
