### ISSUE TITLE
fake classes need toString()

### ISSUE THREAD

**Issue by yegor256** [zerocracy/jstk#22]
fake classes need toString()

**Comment by 0crat** [comment]
Job `gh:zerocracy/jstk#22` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3345](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.5`

**Comment by 0crat** [comment]
Job `gh:zerocracy/jstk#22` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3375](http://www.0crat.com/u/yegor256).
