### ISSUE TITLE
Farm and Project must be closeable too

### ISSUE THREAD

**Issue by yegor256** [zerocracy/jstk#31]
Farm and Project must be closeable too

**Comment by 0crat** [comment]
Job `gh:zerocracy/jstk#31` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4760](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4760](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`
